version: '3.8'

services:
  mysql:
    container_name: todo
    image: mysql:8.3.0
    restart: always
    command:
      --default-authentication-plugin=caching_sha2_password

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  mysql2:
    container_name: comments
    image: mysql:8.3.0
    restart: always
    command:
      --default-authentication-plugin=caching_sha2_password

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comments
    ports:
      - "3307:3306"
    volumes:
      - mysql2:/var/lib/mysql
volumes:
  mysql:
  mysql2: